## Load data

In [1]:
import data




forms_df,cognates_df,lects_df = data.load_romance_dataset()


Loading data...
Loaded data.


## Filter data

In [2]:
forms_df_nonempty = forms_df[~forms_df["Form"].isin(["Ø","?"])]
forms_df_1cognate = forms_df_nonempty[forms_df_nonempty["Cognateset_ID"].apply(len)==1].copy()
forms_df_1cognate["Cognateset_ID_first"] = forms_df_1cognate["Cognateset_ID"].apply(lambda x: x[0])
display(forms_df_1cognate)

ID                   Language_ID                    Cell  \
0            form_0   Catalan_Western_from_Lleida                   [INF]   
1            form_1   Catalan_Western_from_Lleida                   [GER]   
2            form_2   Catalan_Western_from_Lleida              [PST-PTCP]   
3            form_3   Catalan_Western_from_Lleida              [IMP, 2SG]   
4            form_4   Catalan_Western_from_Lleida              [IMP, 2SG]   
...             ...                           ...                     ...   
155024  form_155024  Italic_Latino-Faliscan_Latin  [PST-PTCP, PL, NOM, F]   
155025  form_155025  Italic_Latino-Faliscan_Latin  [PST-PTCP, PL, NOM, N]   
155026  form_155026  Italic_Latino-Faliscan_Latin  [PST-PTCP, PL, ACC, M]   
155027  form_155027  Italic_Latino-Faliscan_Latin  [PST-PTCP, PL, ACC, F]   
155028  form_155028  Italic_Latino-Faliscan_Latin  [PST-PTCP, PL, ACC, N]   

             Form Cognateset_ID Cognateset_ID_first  
0         ˈtindɾe      [tenere]              tenere  
1          teˈnin      [tenere]              tenere  
2         tiŋˈgut      [tenere]              tenere  
3         ˈtiŋges      [tenere]              tenere  
4         ˈtiŋgos      [tenere]              tenere  
...           ...           ...                 ...  
155024   wolaːtaj      [uolare]              uolare  
155025    wolaːta      [uolare]              uolare  
155026  wolaːtoːs      [uolare]              uolare  
155027  wolaːtaːs      [uolare]              uolare  
155028    wolaːta      [uolare]              uolare  

[90511 rows x 6 columns]

## Filter on Latin inflection classes

In [3]:
forms_df_merge = forms_df_1cognate.merge(right=cognates_df, left_on="Cognateset_ID_first", right_on="ID")
display(forms_df_merge.groupby("Language_ID").count().sort_values(by="ID_x", ascending=False).head(10))

latin_conjugation_df = forms_df_merge[~forms_df_merge["Latin_Conjugation"].isnull()]
print(len(latin_conjugation_df))
display(latin_conjugation_df.groupby("Language_ID").count().sort_values(by="ID_x", ascending=False).head(10))

#French_Modern_Standard and Romanian_Modern_Standard seem interesting

ID_x   Cell   Form  Cognateset_ID  \
Language_ID                                                                    
Italic_Latino-Faliscan_Latin              15651  15651  15651          15651   
Swiss_Raeto-Romance_Surselvan              4448   4448   4448           4448   
Galego-Portuguese_Portuguese               2903   2903   2903           2903   
French_Modern_Standard                     2854   2854   2854           2854   
Swiss_Raeto-Romance_Puter_Upper_Engadine   2847   2847   2847           2847   
Spanish_Modern_Standard                    2436   2436   2436           2436   
Italian_Central_Modern_Standard            2155   2155   2155           2155   
Romanian_Modern_Standard                   2100   2100   2100           2100   
Occitan_Southern_Provencal_from_Nice       1912   1912   1912           1912   
French_Franc-Comtois_from_Pierrecourt      1710   1710   1710           1710   

                                          Cognateset_ID_first   ID_y  Etymon  \
Language_ID                                                                    
Italic_Latino-Faliscan_Latin                            15651  15651   15651   
Swiss_Raeto-Romance_Surselvan                            4448   4448    4448   
Galego-Portuguese_Portuguese                             2903   2903    2903   
French_Modern_Standard                                   2854   2854    2854   
Swiss_Raeto-Romance_Puter_Upper_Engadine                 2847   2847    2847   
Spanish_Modern_Standard                                  2436   2436    2436   
Italian_Central_Modern_Standard                          2155   2155    2155   
Romanian_Modern_Standard                                 2100   2100    2100   
Occitan_Southern_Provencal_from_Nice                     1912   1912    1912   
French_Franc-Comtois_from_Pierrecourt                    1710   1710    1710   

                                          Derived_from  \
Language_ID                                              
Italic_Latino-Faliscan_Latin                      2344   
Swiss_Raeto-Romance_Surselvan                      383   
Galego-Portuguese_Portuguese                       124   
French_Modern_Standard                             381   
Swiss_Raeto-Romance_Puter_Upper_Engadine           147   
Spanish_Modern_Standard                            108   
Italian_Central_Modern_Standard                     96   
Romanian_Modern_Standard                           148   
Occitan_Southern_Provencal_from_Nice                48   
French_Franc-Comtois_from_Pierrecourt              100   

                                          Language_of_the_etymon  \
Language_ID                                                        
Italic_Latino-Faliscan_Latin                               15651   
Swiss_Raeto-Romance_Surselvan                               4448   
Galego-Portuguese_Portuguese                                2903   
French_Modern_Standard                                      2854   
Swiss_Raeto-Romance_Puter_Upper_Engadine                    2847   
Spanish_Modern_Standard                                     2436   
Italian_Central_Modern_Standard                             2155   
Romanian_Modern_Standard                                    2100   
Occitan_Southern_Provencal_from_Nice                        1912   
French_Franc-Comtois_from_Pierrecourt                       1710   

                                          Latin_Conjugation  Part_Of_Speech  \
Language_ID                                                                   
Italic_Latino-Faliscan_Latin                          15651           15651   
Swiss_Raeto-Romance_Surselvan                          2980            4448   
Galego-Portuguese_Portuguese                           2713            2903   
French_Modern_Standard                                 2700            2854   
Swiss_Raeto-Romance_Puter_Upper_Engadine               2726            2847   
Spanish_Modern_Standard                               

86290


ID_x   Cell   Form  Cognateset_ID  \
Language_ID                                                                    
Italic_Latino-Faliscan_Latin              15651  15651  15651          15651   
Swiss_Raeto-Romance_Surselvan              2980   2980   2980           2980   
Swiss_Raeto-Romance_Puter_Upper_Engadine   2726   2726   2726           2726   
Galego-Portuguese_Portuguese               2713   2713   2713           2713   
French_Modern_Standard                     2700   2700   2700           2700   
Spanish_Modern_Standard                    2328   2328   2328           2328   
Italian_Central_Modern_Standard            2155   2155   2155           2155   
Romanian_Modern_Standard                   1952   1952   1952           1952   
Occitan_Southern_Provencal_from_Nice       1852   1852   1852           1852   
Occitan_Northern_Vivaro-Alpin_from_Seyne   1600   1600   1600           1600   

                                          Cognateset_ID_first   ID_y  Etymon  \
Language_ID                                                                    
Italic_Latino-Faliscan_Latin                            15651  15651   15651   
Swiss_Raeto-Romance_Surselvan                            2980   2980    2980   
Swiss_Raeto-Romance_Puter_Upper_Engadine                 2726   2726    2726   
Galego-Portuguese_Portuguese                             2713   2713    2713   
French_Modern_Standard                                   2700   2700    2700   
Spanish_Modern_Standard                                  2328   2328    2328   
Italian_Central_Modern_Standard                          2155   2155    2155   
Romanian_Modern_Standard                                 1952   1952    1952   
Occitan_Southern_Provencal_from_Nice                     1852   1852    1852   
Occitan_Northern_Vivaro-Alpin_from_Seyne                 1600   1600    1600   

                                          Derived_from  \
Language_ID                                              
Italic_Latino-Faliscan_Latin                      2344   
Swiss_Raeto-Romance_Surselvan                      383   
Swiss_Raeto-Romance_Puter_Upper_Engadine           147   
Galego-Portuguese_Portuguese                       124   
French_Modern_Standard                             381   
Spanish_Modern_Standard                            108   
Italian_Central_Modern_Standard                     96   
Romanian_Modern_Standard                           148   
Occitan_Southern_Provencal_from_Nice                48   
Occitan_Northern_Vivaro-Alpin_from_Seyne           144   

                                          Language_of_the_etymon  \
Language_ID                                                        
Italic_Latino-Faliscan_Latin                               15651   
Swiss_Raeto-Romance_Surselvan                               2980   
Swiss_Raeto-Romance_Puter_Upper_Engadine                    2726   
Galego-Portuguese_Portuguese                                2713   
French_Modern_Standard                                      2700   
Spanish_Modern_Standard                                     2328   
Italian_Central_Modern_Standard                             2155   
Romanian_Modern_Standard                                    1952   
Occitan_Southern_Provencal_from_Nice                        1852   
Occitan_Northern_Vivaro-Alpin_from_Seyne                    1600   

                                          Latin_Conjugation  Part_Of_Speech  \
Language_ID                                                                   
Italic_Latino-Faliscan_Latin                          15651           15651   
Swiss_Raeto-Romance_Surselvan                          2980            2980   
Swiss_Raeto-Romance_Puter_Upper_Engadine               2726            2726   
Galego-Portuguese_Portuguese                           2713            2713   
French_Modern_Standard                                 2700            2700   
Spanish_Modern_Standard                               

## Create dataset per language

In [28]:
import pandas as pd
import numpy as np

# Diacritics are counted as separate character

def get_sound_inventory(forms):
    sound_inventory = list(set(list("".join(forms))))
    max_form_len = max([len(x) for x in forms])
    return sound_inventory, max_form_len


def create_onehot_inflections(inflections):
    n_inflections = len(inflections)
    inflection_inventory = list(inflections.unique())
    inflection_inventory_size = len(inflection_inventory)
    array = np.zeros(shape=(n_inflections, inflection_inventory_size))
    for infl_row, inflection in enumerate(inflections):
        hot_index = inflection_inventory.index(inflection)
        array[infl_row, hot_index] = 1
    return array, inflection_inventory
        
        
    

def create_onehot_forms(forms, empty_symbol=True):
    sounds, max_form_len = get_sound_inventory(forms)
    n_forms = len(forms)
    if empty_symbol:
        sounds.append(".")
    n_sounds = len(sounds)
    #print(sounds)
    #print(f"n_forms: {n_forms}")
    #print(f"n_sounds: {n_sounds}")
    #print(f"max_form_len: {max_form_len}")
    array = np.zeros(shape=(n_forms, n_sounds * max_form_len))
    for form_row, form in enumerate(forms):
        #print(form)
        form_len = len(form)
        for char_position in range(max_form_len):
            if char_position < form_len:
                char = form[char_position]
                char_hot_index = sounds.index(char)
                array[form_row, char_position*n_sounds+char_hot_index] = 1
                #print(f"Char position {char_position} within form: {char}. Hot index: {char_hot_index}. Index: {form_row, char_position*n_sounds+char_hot_index}")
            else: ## Char_position >= form_len; so word shorter than the longest word
                if empty_symbol:
                    ## Create symbol for these positions
                    empty_hot_index = sounds.index(".")
                    array[form_row, char_position*n_sounds+empty_hot_index] = 1
                    #print(f"Char position {char_position} OUTSIDE form. Hot index: {empty_hot_index}. Index: {form_row, char_position*n_sounds+empty_hot_index}")
                ## Else: just leave the 0000s for empty symbol
    return array, sounds
                    
                
    

def create_language_dataset(df, language, empty_symbol=True, language_column = "Language_ID", form_column="Form", inflection_column = "Latin_Conjugation"):
    df_language = df[df[language_column]==language][[form_column, inflection_column]]
    forms_onehot, sound_inventory = create_onehot_forms(df_language[form_column], empty_symbol)
    inflections_onehot, inflection_inventory = create_onehot_inflections(df_language[inflection_column])
    return forms_onehot, inflections_onehot, inflections

forms_onehot, inflections_onehot, inflections = create_language_dataset(latin_conjugation_df, "French_Modern_Standard", empty_symbol=False)

['II', 'special', 'IV', 'III', 'I']
47       II
48       II
49       II
50       II
51       II
         ..
65524    IV
65525    IV
65526    IV
65527    IV
65528    IV
Name: Latin_Conjugation, Length: 2700, dtype: object
[[1. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0.]
 ...
 [0. 0. 1. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 1. 0. 0.]]


## Plot data (before running model)

In [ ]:
## Iff Language_of_the_etymon is Latin, it has inflection classes
# print(cognates_df[~cognates_df["Latin_Conjugation"].isnull()]["Language_of_the_etymon"].unique()) # only if
# print(cognates_df[cognates_df["Latin_Conjugation"].isnull()]["Language_of_the_etymon"].unique()) # if

## Get lemma for every form in cognateset id list
#cognates_df_lookup = cognates_df.set_index("ID")
#forms_df["inflection_classes"] = forms_df["Cognateset_ID"].apply(lambda cids: [cognates_df_lookup.loc[cid]["Latin_Conjugation"] for cid in cids])